# Generated by Django 5.0.7 on 2024-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_destination_transport_remove_newtrip_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtrip',
            name='destination',
            field=models.ManyToManyField(blank=True, null=True, to='base.destination'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='transport',
            field=models.ManyToManyField(blank=True, null=True, to='base.transport'),
        ),
    ]
