# Generated by Django 5.0.7 on 2024-07-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_trip_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
