# Generated by Django 5.0.7 on 2024-08-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_newtrip_destination_alter_newtrip_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
