# Generated by Django 5.0.7 on 2024-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_destination_name_alter_transport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtrip',
            name='destination',
            field=models.ManyToManyField(blank=True, to='base.destination'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='transport',
            field=models.ManyToManyField(blank=True, to='base.transport'),
        ),
    ]
