# Generated by Django 5.0.7 on 2024-08-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_newtrip_destination_alter_newtrip_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('plane', 'Plane'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
