# Generated by Django 5.0.7 on 2024-08-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_transport_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtrip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='newtrip',
            name='transport',
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.destination')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.transport')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.newtrip')),
            ],
        ),
    ]
