# Generated by Django 5.0.7 on 2024-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_newtrip_destination_remove_newtrip_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bus', 'Bus'), ('bike', 'Bike'), ('train', 'Train'), ('plane', 'Plane'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
