# Generated by Django 5.0.7 on 2024-08-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_transport_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtrip',
            old_name='end_date',
            new_name='intEndDate',
        ),
        migrations.RenameField(
            model_name='newtrip',
            old_name='start_date',
            new_name='intStartDate',
        ),
        migrations.RenameField(
            model_name='newtrip',
            old_name='title',
            new_name='strTripName',
        ),
    ]
