# Generated by Django 5.0.7 on 2024-08-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtrip',
            name='strTripName',
            field=models.CharField(max_length=50),
        ),
    ]
