# Generated by Django 5.0.7 on 2024-08-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_leg_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.newtrip'),
        ),
    ]
