# Generated by Django 5.1.1 on 2024-09-12 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_checklistitem_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='trip',
            new_name='dictTripLst',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='title',
            new_name='strItem',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='strLoc',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='name',
            new_name='strTran',
        ),
        migrations.RenameModel(
            old_name='newTrip',
            new_name='Trip',
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictTripLst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trip')),
                ('strLoc', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.destination')),
                ('strTran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.transport')),
            ],
        ),
        migrations.DeleteModel(
            name='Leg',
        ),
    ]
