# Generated by Django 5.1.1 on 2024-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_stritem_checklistitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
